NetInfo for buyer app
housinghq/react-native-net-handler pull request #6
Opened 2019-11-19 12:20 UTC by onkarpandit

2019-11-25 13:09 UTC, Sunil18 requested changes

2019-11-25 13:09 UTC, Sunil18 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +        NetworkConnection network = new NetworkConnection();
getInstance()

2019-11-25 13:09 UTC, Sunil18 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +            mContext
Can avoid repeated getJSModule call.

2019-11-25 13:14 UTC, manthan-25 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +        receivedMessage.putBoolean("statusChange", status);
can change key to "status" or "isConnected"

2019-11-25 13:15 UTC, manthan-25 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +    private static final String EVENT_CHANGE = "net-handler:Status Change";
can change to "connectionChange"

2019-11-25 13:16 UTC, manthan-25 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +        if (mContext!=null && !status==currentStatus){
can use !=

2019-11-25 13:30 UTC, manthan-25 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +    private mContext = null;
should be private ReactApplicationContext mcontext

2019-11-26 06:08 UTC, Sunil18 requested changes

2019-11-26 06:08 UTC, Sunil18 commented on android/src/main/java/com/reactlibrary/NetworkBroadcastReceiver.java
> +        boolean currentStatus = netInfo.getConnectionStatus();
null check for netInfo

2019-11-26 06:20 UTC, Sunil18 approved these changes

2019-11-26 06:20 UTC, merged